#!/usr/bin/env groovy
node {
    timestamps {
        stage 'Build'
        checkout scm
        sh "gradle clean build"
        publishHTML (target: [
              allowMissing: false,
              alwaysLinkToLastBuild: false,
              keepAll: true,
              reportDir: 'reports',
              reportFiles: '*',
              reportName: "Test Report"
            ])
    }
}
