#!/usr/bin/env groovy
node {
    timestamps {
        stage 'Build'
        checkout scm
        sh "gradle clean build"

        archive (includes: 'build/reports/tests')

        publishHTML (target: [
              allowMissing: false,
              alwaysLinkToLastBuild: false,
              keepAll: true,
              reportDir: 'reports/tests/test',
              reportFiles: 'index.html',
              reportName: "Tests"
            ])
    }
}
